"""One-time generator for services/curricula_hi.json.

Run manually (`python scripts/generate_curricula_hi.py` from backend/) whenever
CURRICULA's user-facing fields change. NOT run at request time or import time --
the output is a static, reviewed, committed JSON file; services/curricula.py
reads it the same way it reads any other static data.

The committed curricula_hi.json was hand-translated, not generated by this
script -- the configured GEMINI_API_KEY at write time was invalid, so this
ran and failed. Keeping the script for whoever next has a working key and
wants to regenerate from a changed CURRICULA rather than hand-editing JSON;
always re-read the diff before committing its output, the same as any
translation, automated or not.

Only translates fields actually rendered to a learner today: curriculum name/
domain/description/audience/level_band, and each competency's label/
description. Deliberately does NOT translate COMPETENCY_SOURCES' citation
excerpts or SOURCES' title/publisher -- those are literal references to real
government documents, and paraphrase-translating a citation misrepresents it
rather than localizing it. Those fields are not shown to learners today
(confirmed: neither stats/page.jsx nor AcademyHub.jsx renders them).
"""
import asyncio
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from services.curricula import CURRICULA  # noqa: E402

CURRICULUM_FIELDS = ["name", "domain", "description", "audience", "level_band"]
COMPETENCY_FIELDS = ["label", "description"]


def build_source_payload() -> dict:
    payload = {}
    for slug, curriculum in CURRICULA.items():
        payload[slug] = {field: curriculum[field] for field in CURRICULUM_FIELDS}
        payload[slug]["competencies"] = {
            item["id"]: {field: item[field] for field in COMPETENCY_FIELDS}
            for item in curriculum["competencies"]
        }
    return payload


async def translate(payload: dict) -> dict:
    import google.generativeai as genai

    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key:
        raise SystemExit("GEMINI_API_KEY must be set to run this generator")

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel(os.getenv("LLM_MODEL", "gemini-flash-lite-latest"))

    prompt = f"""Translate every string value in this JSON object into formal,
plain, modern standard Hindi (Devanagari script) suitable for a professional
government-training platform aimed at Indian civil servants. Preserve every
key exactly as given -- translate ONLY the string values. Preserve any
acronym or proper noun that should stay in English (e.g. "DSA", "GIS", "SQL",
"AI", "SDG") by keeping it in Latin script within the Hindi sentence, the way
a real Hindi government document would. Return ONLY the translated JSON
object, valid JSON, no markdown fences, no commentary, with the exact same
structure (same keys, same nesting) as the input.

INPUT:
{json.dumps(payload, ensure_ascii=False, indent=2)}
"""

    response = await asyncio.wait_for(
        asyncio.to_thread(model.generate_content, prompt), timeout=120.0
    )
    text = response.text.strip()
    if text.startswith("```"):
        text = text.split("```")[1]
        if text.startswith("json"):
            text = text[4:]
    return json.loads(text.strip())


def validate_shape(source: dict, translated: dict) -> None:
    for slug, curriculum in source.items():
        if slug not in translated:
            raise ValueError(f"Missing curriculum in translation: {slug}")
        for field in CURRICULUM_FIELDS:
            if field not in translated[slug] or not translated[slug][field]:
                raise ValueError(f"Missing {slug}.{field} in translation")
        for comp_id, comp in curriculum["competencies"].items():
            translated_comp = translated[slug].get("competencies", {}).get(comp_id)
            if not translated_comp:
                raise ValueError(f"Missing competency in translation: {slug}.{comp_id}")
            for field in COMPETENCY_FIELDS:
                if field not in translated_comp or not translated_comp[field]:
                    raise ValueError(f"Missing {slug}.{comp_id}.{field} in translation")


async def main() -> None:
    source = build_source_payload()
    translated = await translate(source)
    validate_shape(source, translated)
    out_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "services",
        "curricula_hi.json",
    )
    with open(out_path, "w", encoding="utf-8") as handle:
        json.dump(translated, handle, ensure_ascii=False, indent=2)
        handle.write("\n")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    asyncio.run(main())
