"""Lane 4 (Content AI, RAG & Evaluation) — Provenance & Data Models.

Defines immutable source representations, locators, chunks, access context,
citations, item review lifecycles, and assistant response states.
"""
from __future__ import annotations

import dataclasses
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any
import uuid


def generate_uuid() -> str:
    return str(uuid.uuid4())


class ItemReviewState(str, Enum):
    """Lifecycle state machine for generated assessment items."""
    DRAFT = "draft"
    AUTO_CHECKED = "auto_checked"
    EXPERT_REVIEW = "expert_review"
    APPROVED = "approved"
    PILOT = "pilot"
    PUBLISHED = "published"
    RETIRED = "retired"


class AssistantResponseStatus(str, Enum):
    """Explicit status classification for learner assistant responses."""
    SUPPORTED = "supported"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"
    OUT_OF_SCOPE = "out_of_scope"
    PROMPT_INJECTION_DETECTED = "prompt_injection_detected"
    RETRIEVAL_FAILURE = "retrieval_failure"
    SYSTEM_FAILURE = "system_failure"


@dataclass(frozen=True)
class SourceLocator:
    """Precise location of a chunk within its original source artifact."""
    locator_type: str  # page | slide | section | paragraph | timecode
    index: int | str
    label: str  # e.g., "Page 4", "Slide 12", "Section 3.2", "00:04:15 - 00:04:45"
    start_char: int = 0
    end_char: int = 0
    start_timecode: str | None = None
    end_timecode: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return dataclasses.asdict(self)


@dataclass
class SourceVersion:
    """Immutable record of an ingested document version."""
    source_id: str
    version: int
    sha256: str
    filename: str
    content_type: str
    character_count: int
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return dataclasses.asdict(self)


@dataclass
class Chunk:
    """Atomic text unit with immutable provenance and access scope."""
    chunk_id: str
    source_id: str
    source_version: int
    text: str
    locators: list[SourceLocator]
    tenant_id: str = "default"
    allowed_roles: list[str] = field(default_factory=lambda: ["learner", "trainer", "admin"])
    token_count: int = 0
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "chunk_id": self.chunk_id,
            "source_id": self.source_id,
            "source_version": self.source_version,
            "text": self.text,
            "locators": [loc.to_dict() for loc in self.locators],
            "tenant_id": self.tenant_id,
            "allowed_roles": self.allowed_roles,
            "token_count": self.token_count,
            "metadata": self.metadata,
        }


@dataclass(frozen=True)
class AccessContext:
    """Caller context for pre-retrieval access enforcement."""
    tenant_id: str = "default"
    user_id: str = "anonymous"
    roles: tuple[str, ...] = ("learner",)

    def can_access(self, chunk: Chunk) -> bool:
        if chunk.tenant_id != self.tenant_id:
            return False
        if not chunk.allowed_roles:
            return True
        return any(role in chunk.allowed_roles for role in self.roles)


@dataclass
class Citation:
    """Verifiable source citation linking a claim to an immutable chunk."""
    citation_id: str
    chunk_id: str
    source_id: str
    source_version: int
    filename: str
    locator_label: str
    quote: str
    confidence_score: float = 1.0

    def to_dict(self) -> dict[str, Any]:
        return dataclasses.asdict(self)


@dataclass
class RetrievedChunk:
    """Chunk result from access-filtered retrieval."""
    chunk: Chunk
    relevance_score: float
    matched_terms: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "chunk": self.chunk.to_dict(),
            "relevance_score": round(self.relevance_score, 4),
            "matched_terms": self.matched_terms,
        }


@dataclass
class AssistantResponse:
    """Grounded response generated by the Learner Assistant."""
    query: str
    answer: str
    status: AssistantResponseStatus
    citations: list[Citation] = field(default_factory=list)
    retrieved_chunks: list[RetrievedChunk] = field(default_factory=list)
    abstention_reason: str | None = None
    model_version: str = "gemini-flash-lite-latest"
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> dict[str, Any]:
        return {
            "query": self.query,
            "answer": self.answer,
            "status": self.status.value,
            "citations": [c.to_dict() for c in self.citations],
            "retrieved_chunks": [rc.to_dict() for rc in self.retrieved_chunks],
            "abstention_reason": self.abstention_reason,
            "model_version": self.model_version,
            "created_at": self.created_at,
        }


@dataclass
class QuizQuestionItem:
    """Assessment item with full source grounding and review lifecycle state."""
    question_id: str
    source_id: str
    source_version: int
    chunk_ids: list[str]
    source_locators: list[SourceLocator]
    question: str
    options: list[str]
    answer_index: int
    explanation: str
    source_excerpt: str
    competency: str = "Source comprehension"
    bloom_level: str = "understand"
    review_state: ItemReviewState = ItemReviewState.DRAFT
    validation_notes: list[str] = field(default_factory=list)
    reviewer_id: str | None = None
    reviewed_at: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "question_id": self.question_id,
            "source_id": self.source_id,
            "source_version": self.source_version,
            "chunk_ids": self.chunk_ids,
            "source_locators": [loc.to_dict() for loc in self.source_locators],
            "question": self.question,
            "options": self.options,
            "answer_index": self.answer_index,
            "explanation": self.explanation,
            "source_excerpt": self.source_excerpt,
            "competency": self.competency,
            "bloom_level": self.bloom_level,
            "review_state": self.review_state.value,
            "validation_notes": self.validation_notes,
            "reviewer_id": self.reviewer_id,
            "reviewed_at": self.reviewed_at,
        }
