"""Golden fixture tests for the gap/pathway engine.

SIH26101_TEAM_ORCHESTRATION.md section 5, Lane 3 acceptance evidence:
"Golden policy fixtures produce stable gaps and pathways." Every existing
Lane 3 test checks a specific field or behavior; these instead pin the
*entire* output for six realistic scenarios and fail on any drift, intended
or not.

Fixtures live in fixtures/golden_pathways/*.json, generated by
fixtures/generate_golden_fixtures.py (a manual tool, not imported here).
Each JSON's numbers were hand-verified against the documented formulas
before being trusted -- see the commit history for the by-hand arithmetic on
the blend/role-target scenarios. A fixture is not "golden" merely because a
generator produced it; it is golden because a human checked it once and it
has not silently drifted since.

`courses` is stripped before comparison: it comes from Lane 5's
services/learning_catalog.py, reads two environment variables, and is not a
Lane 3 policy output -- pinning it here would make this lane's tests fail for
a reason entirely outside this lane's control.
"""
import json
from pathlib import Path

import pytest

from services.learning_engine import analyse_competencies

FIXTURES_DIR = Path(__file__).parent / "fixtures" / "golden_pathways"
FIXTURE_FILES = sorted(FIXTURES_DIR.glob("*.json"))


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _run(fixture: dict) -> dict:
    result = analyse_competencies(**fixture["input"])
    result.pop("courses", None)
    return result


# ─── fixture set integrity ───

def test_at_least_six_golden_scenarios_exist():
    # A minimum floor so this file can't quietly lose coverage if a fixture
    # is accidentally deleted.
    assert len(FIXTURE_FILES) >= 6


@pytest.mark.parametrize("path", FIXTURE_FILES, ids=lambda p: p.stem)
def test_fixture_file_has_the_required_shape(path):
    fixture = _load(path)
    assert set(fixture) == {"description", "input", "expected"}
    assert fixture["description"].strip()
    assert "curriculum_slug" in fixture["input"]
    assert "courses" not in fixture["expected"]


# ─── the actual golden comparison ───

@pytest.mark.parametrize("path", FIXTURE_FILES, ids=lambda p: p.stem)
def test_engine_output_matches_the_golden_fixture_exactly(path):
    fixture = _load(path)
    actual = _run(fixture)
    assert actual == fixture["expected"], (
        f"{path.name} drifted from the pinned output. If this is an "
        "intentional policy change, regenerate with "
        "fixtures/generate_golden_fixtures.py, hand-verify the new numbers, "
        "and commit the diff deliberately -- do not accept a drift you "
        "cannot explain."
    )


# ─── literal determinism: same input, same process, called twice ───

@pytest.mark.parametrize("path", FIXTURE_FILES, ids=lambda p: p.stem)
def test_repeated_calls_with_identical_input_are_byte_identical(path):
    fixture = _load(path)
    first = _run(fixture)
    second = _run(fixture)
    assert first == second
    # Not just structurally equal -- the JSON serialization itself must
    # match, which also catches key-ordering or float-formatting drift that
    # a dict == comparison alone could mask.
    assert json.dumps(first, sort_keys=True) == json.dumps(second, sort_keys=True)


# ─── specific claims worth pinning by name, not just by snapshot ───

def test_golden_blend_scenario_priority_is_high_not_critical():
    # Hand-computed: observed = 2.0*0.65 + 4.0*0.35 = 2.7, role target 5
    # (Statistical Officer override), gap = 2.3 -- above the 1.5 "high"
    # threshold but below the 2.5 "critical" one. A boundary worth naming
    # explicitly so a threshold change is caught even if someone edits the
    # fixture file by hand without re-running the generator.
    fixture = _load(FIXTURES_DIR / "blended_with_role_target_override.json")
    row = next(c for c in fixture["expected"]["competencies"] if c["competency_id"] == "os_official_statistics")
    assert row["gap"] == 2.3
    assert row["priority"] == "high"


def test_golden_department_scenario_prefers_assignment_over_department():
    fixture = _load(FIXTURES_DIR / "department_and_assignment_targeting.json")
    row = next(c for c in fixture["expected"]["competencies"] if c["competency_id"] == "os_sampling_design")
    assert row["matched_field"] == "current_assignment"

    row = next(c for c in fixture["expected"]["competencies"] if c["competency_id"] == "os_official_statistics")
    assert row["matched_field"] == "department"


def test_golden_mixed_pathway_keeps_prerequisites_before_dependents():
    fixture = _load(FIXTURES_DIR / "mixed_coverage_multi_step_pathway.json")
    order = {step["competency_id"]: step["step"] for step in fixture["expected"]["pathway"]}
    if "os_sampling_design" in order and "os_data_collection" in order:
        assert order["os_data_collection"] < order["os_sampling_design"]
    if "os_data_collection" in order and "os_statistical_foundations" in order:
        assert order["os_statistical_foundations"] < order["os_data_collection"]
