"""
Question SQLAlchemy model — stores AI-generated questions.
"""
import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, DateTime
from db.database import Base


def generate_uuid():
    return str(uuid.uuid4())


class Question(Base):
    __tablename__ = "questions"

    question_id = Column(String, primary_key=True, default=generate_uuid)
    topic = Column(String, nullable=False)
    difficulty = Column(String, nullable=False)  # easy | medium | hard
    question_text = Column(String, nullable=False)
    expected_answer = Column(String, nullable=False)
    hint = Column(String, nullable=True)
    # Damage this question deals if answered perfectly (NLP score of 1.0);
    # actual damage is max_damage * score, so a hard question with a high
    # ceiling always outdamages an easy one at the same score. Generated by
    # the AI layer alongside the question text (see services/llm_engine.py).
    max_damage = Column(Integer, default=80)
    generated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
