"""baseline current schema

Revision ID: 65bc8695fadc
Revises:
Create Date: 2026-08-31 20:45:35.650283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65bc8695fadc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dungeons',
    sa.Column('dungeon_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('curriculum_slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dungeon_id')
    )
    op.create_index(op.f('ix_dungeons_curriculum_slug'), 'dungeons', ['curriculum_slug'], unique=False)
    op.create_table('guilds',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('raid_boss_id', sa.String(), nullable=True),
    sa.Column('raid_active', sa.Boolean(), nullable=True),
    sa.Column('raid_boss_hp', sa.Integer(), nullable=True),
    sa.Column('raid_boss_damage', sa.Integer(), nullable=True),
    sa.Column('raid_topic_assignments', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('expected_answer', sa.String(), nullable=False),
    sa.Column('hint', sa.String(), nullable=True),
    sa.Column('max_damage', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('guild_id', sa.String(), nullable=True),
    sa.Column('hint_tokens', sa.Integer(), nullable=True),
    sa.Column('hero_id', sa.String(), nullable=True),
    sa.Column('pending_xp_multiplier', sa.Float(), nullable=True),
    sa.Column('pending_verdict_boost', sa.Boolean(), nullable=True),
    sa.Column('pending_force_correct', sa.Boolean(), nullable=True),
    sa.Column('powerup_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('powerup_uses_this_window', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=True)
    op.create_table('rooms',
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('dungeon_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('enemy_count', sa.Integer(), nullable=True),
    sa.Column('is_boss', sa.Boolean(), nullable=True),
    sa.Column('is_unlocked', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dungeon_id'], ['dungeons.dungeon_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('accuracy_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('recent_accuracy', sa.Float(), nullable=True),
    sa.Column('last_5_results', sa.JSON(), nullable=True),
    sa.Column('mastered', sa.Boolean(), nullable=True),
    sa.Column('damage_dealt', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'topic', name='uq_player_topic')
    )
    op.create_index(op.f('ix_accuracy_history_player_id'), 'accuracy_history', ['player_id'], unique=False)
    op.create_table('competency_assessments',
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('curriculum_slug', sa.String(), nullable=False),
    sa.Column('self_ratings', sa.JSON(), nullable=True),
    sa.Column('measured_scores', sa.JSON(), nullable=True),
    sa.Column('skill_gaps', sa.JSON(), nullable=True),
    sa.Column('recommended_course_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index(op.f('ix_competency_assessments_curriculum_slug'), 'competency_assessments', ['curriculum_slug'], unique=False)
    op.create_index(op.f('ix_competency_assessments_player_id'), 'competency_assessments', ['player_id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('dungeon_id', sa.String(), nullable=False),
    sa.Column('current_room_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dungeon_id'], ['dungeons.dungeon_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('learner_profiles',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('job_role', sa.String(), nullable=True),
    sa.Column('current_assignment', sa.String(), nullable=True),
    sa.Column('educational_qualifications', sa.String(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('previous_trainings', sa.JSON(), nullable=True),
    sa.Column('career_goal', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('target_domains', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_learner_profiles_player_id'), 'learner_profiles', ['player_id'], unique=True)
    op.create_table('learning_materials',
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('text_excerpt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_index(op.f('ix_learning_materials_player_id'), 'learning_materials', ['player_id'], unique=False)
    op.create_index(op.f('ix_learning_materials_sha256'), 'learning_materials', ['sha256'], unique=False)
    op.create_table('submissions',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('player_answer', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('damage_multiplier', sa.Float(), nullable=True),
    sa.Column('damage_dealt', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('generated_quizzes',
    sa.Column('quiz_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('generation_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['learning_materials.material_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_index(op.f('ix_generated_quizzes_material_id'), 'generated_quizzes', ['material_id'], unique=False)
    op.create_index(op.f('ix_generated_quizzes_player_id'), 'generated_quizzes', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_quizzes_player_id'), table_name='generated_quizzes')
    op.drop_index(op.f('ix_generated_quizzes_material_id'), table_name='generated_quizzes')
    op.drop_table('generated_quizzes')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_learning_materials_sha256'), table_name='learning_materials')
    op.drop_index(op.f('ix_learning_materials_player_id'), table_name='learning_materials')
    op.drop_table('learning_materials')
    op.drop_index(op.f('ix_learner_profiles_player_id'), table_name='learner_profiles')
    op.drop_table('learner_profiles')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_competency_assessments_player_id'), table_name='competency_assessments')
    op.drop_index(op.f('ix_competency_assessments_curriculum_slug'), table_name='competency_assessments')
    op.drop_table('competency_assessments')
    op.drop_index(op.f('ix_accuracy_history_player_id'), table_name='accuracy_history')
    op.drop_table('accuracy_history')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_table('players')
    op.drop_table('questions')
    op.drop_table('guilds')
    op.drop_index(op.f('ix_dungeons_curriculum_slug'), table_name='dungeons')
    op.drop_table('dungeons')
    # ### end Alembic commands ###
