"""add judgment scenarios

Revision ID: 7d9c7a7c14fe
Revises: 09bfedae1a90
Create Date: 2026-09-12 13:59:23.234075

Adds the branching "Judgment Simulation" content type: `judgment_scenarios`
(the shared, hand-authored decision trees -- see
data/judgment_scenarios.json) and `judgment_scenario_attempts` (a learner's
real, completed runs through one). See models/judgment_scenario.py for the
full rationale, including why a completed attempt writes an EvidenceRecord
and updates AccuracyHistory exactly like labs/sampling_lab.py's submission
flow.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9c7a7c14fe'
down_revision: Union[str, None] = '09bfedae1a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judgment_scenarios',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('competency_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('situation_brief', sa.String(), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('start_node_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_index(op.f('ix_judgment_scenarios_competency_id'), 'judgment_scenarios', ['competency_id'], unique=False)
    op.create_table('judgment_scenario_attempts',
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('path_taken', sa.JSON(), nullable=False),
    sa.Column('recommended_choice_count', sa.Integer(), nullable=False),
    sa.Column('total_choice_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['judgment_scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_judgment_scenario_attempts_player_id'), 'judgment_scenario_attempts', ['player_id'], unique=False)
    op.create_index(op.f('ix_judgment_scenario_attempts_scenario_id'), 'judgment_scenario_attempts', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judgment_scenario_attempts_scenario_id'), table_name='judgment_scenario_attempts')
    op.drop_index(op.f('ix_judgment_scenario_attempts_player_id'), table_name='judgment_scenario_attempts')
    op.drop_table('judgment_scenario_attempts')
    op.drop_index(op.f('ix_judgment_scenarios_competency_id'), table_name='judgment_scenarios')
    op.drop_table('judgment_scenarios')
    # ### end Alembic commands ###
