"""add live quiz sessions

Revision ID: 951dbad5f9f6
Revises: 7d9c7a7c14fe
Create Date: 2026-09-13 16:45:50.199104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951dbad5f9f6'
down_revision: Union[str, None] = '7d9c7a7c14fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_quiz_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('quiz_id', sa.String(), nullable=False),
    sa.Column('host_player_id', sa.String(), nullable=False),
    sa.Column('join_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['generated_quizzes.quiz_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_live_quiz_sessions_host_player_id'), 'live_quiz_sessions', ['host_player_id'], unique=False)
    op.create_index(op.f('ix_live_quiz_sessions_join_code'), 'live_quiz_sessions', ['join_code'], unique=True)
    op.create_index(op.f('ix_live_quiz_sessions_quiz_id'), 'live_quiz_sessions', ['quiz_id'], unique=False)
    op.create_table('live_session_participants',
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['live_quiz_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('participant_id'),
    sa.UniqueConstraint('session_id', 'player_id', name='uq_live_session_participant')
    )
    op.create_index(op.f('ix_live_session_participants_player_id'), 'live_session_participants', ['player_id'], unique=False)
    op.create_index(op.f('ix_live_session_participants_session_id'), 'live_session_participants', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_session_participants_session_id'), table_name='live_session_participants')
    op.drop_index(op.f('ix_live_session_participants_player_id'), table_name='live_session_participants')
    op.drop_table('live_session_participants')
    op.drop_index(op.f('ix_live_quiz_sessions_quiz_id'), table_name='live_quiz_sessions')
    op.drop_index(op.f('ix_live_quiz_sessions_join_code'), table_name='live_quiz_sessions')
    op.drop_index(op.f('ix_live_quiz_sessions_host_player_id'), table_name='live_quiz_sessions')
    op.drop_table('live_quiz_sessions')
    # ### end Alembic commands ###
