"""add identity bindings

Revision ID: cf4271f204a3
Revises: 2baf7d4bd8a2
Create Date: 2026-09-01 01:04:17.476299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4271f204a3'
down_revision: Union[str, None] = '2baf7d4bd8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_bindings',
    sa.Column('binding_id', sa.String(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('binding_id'),
    sa.UniqueConstraint('issuer', 'subject_id', name='uq_identity_binding_subject')
    )
    op.create_index(op.f('ix_identity_bindings_player_id'), 'identity_bindings', ['player_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_bindings_player_id'), table_name='identity_bindings')
    op.drop_table('identity_bindings')
    # ### end Alembic commands ###
