"""
MOCK DATA -- a stand-in for the main backend's real data.

Everything in this file simulates data that, in production, comes from the
main FastAPI backend (accuracy_history is read from its DB and sent to us in
request bodies; player_id is generated by it on session start).

DELETE OR REPLACE WHEN INTEGRATING: once the main backend's /game/answer/submit
is writing real accuracy_history rows, these constants should only be used
inside tests/ -- never imported by services/ or routes/ in production code.

Schema contract (from README section 6, "Accuracy History"):
{
    "<topic_name>": {
        "attempts": int,
        "correct": int,
        "recent_accuracy": float,   # mean of last_5_results
        "last_5_results": [bool, bool, bool, bool, bool],
    },
    ...
}
"""

# MOCK: valid UUID4 string, standing in for a real backend-generated player_id.
MOCK_PLAYER_ID = "550e8400-e29b-41d4-a716-446655440000"

# MOCK: Simulates the main backend's accuracy_history for a brand new player
# who has never answered a single question. Replace with real DB data when
# integrating.
MOCK_ACCURACY_HISTORY_EMPTY = {}

# MOCK: Simulates the main backend's accuracy_history early in a session --
# only "arrays" has been attempted, and the player is struggling with it.
# Replace with real DB data when integrating.
MOCK_ACCURACY_HISTORY_BEGINNER = {
    "arrays": {
        "attempts": 5,
        "correct": 2,
        "recent_accuracy": 0.4,
        "last_5_results": [False, False, True, False, True],
    },
}

# MOCK: Simulates the main backend's accuracy_history mid-session -- "arrays"
# is mastered (unlocking its dependents), while linked_lists/binary_search/
# recursion are all still weak. Note "stacks_queues" is deliberately left
# out of this dict entirely to exercise the "unlocked but never attempted"
# code path in knowledge_graph.py (its only prereq, arrays, is mastered, so
# it should still show up as unlocked even with zero data of its own).
# Replace with real DB data when integrating.
MOCK_ACCURACY_HISTORY_INTERMEDIATE = {
    "arrays": {
        "attempts": 12,
        "correct": 11,
        "recent_accuracy": 0.8,
        "last_5_results": [True, True, True, True, False],
    },
    "linked_lists": {
        "attempts": 8,
        "correct": 5,
        "recent_accuracy": 0.6,
        "last_5_results": [True, False, True, False, True],
    },
    "binary_search": {
        "attempts": 7,
        "correct": 3,
        "recent_accuracy": 0.4,
        "last_5_results": [False, True, False, False, True],
    },
    "recursion": {
        "attempts": 9,
        "correct": 2,
        "recent_accuracy": 0.2,
        "last_5_results": [False, False, True, False, False],
    },
}

# MOCK: Simulates the main backend's accuracy_history late in a session --
# almost every topic is mastered, except dynamic_programming and graphs,
# which the player is actively failing. All 11 README topics are represented.
# Replace with real DB data when integrating.
MOCK_ACCURACY_HISTORY_ADVANCED = {
    "arrays": {
        "attempts": 20,
        "correct": 19,
        "recent_accuracy": 1.0,
        "last_5_results": [True, True, True, True, True],
    },
    "linked_lists": {
        "attempts": 15,
        "correct": 14,
        "recent_accuracy": 1.0,
        "last_5_results": [True, True, True, True, True],
    },
    "stacks_queues": {
        "attempts": 10,
        "correct": 8,
        "recent_accuracy": 0.8,
        "last_5_results": [True, True, True, True, False],
    },
    "binary_search": {
        "attempts": 12,
        "correct": 11,
        "recent_accuracy": 1.0,
        "last_5_results": [True, True, True, True, True],
    },
    "recursion": {
        "attempts": 14,
        "correct": 11,
        "recent_accuracy": 0.8,
        "last_5_results": [True, True, True, True, False],
    },
    "trees": {
        "attempts": 10,
        "correct": 8,
        "recent_accuracy": 0.8,
        "last_5_results": [True, True, True, True, False],
    },
    "binary_search_tree": {
        "attempts": 8,
        "correct": 6,
        "recent_accuracy": 0.8,
        "last_5_results": [True, True, True, False, True],
    },
    "heaps": {
        "attempts": 6,
        "correct": 5,
        "recent_accuracy": 0.8,
        "last_5_results": [True, True, False, True, True],
    },
    "graphs": {
        "attempts": 5,
        "correct": 1,
        "recent_accuracy": 0.2,
        "last_5_results": [False, False, False, False, True],
    },
    "dynamic_programming": {
        "attempts": 5,
        "correct": 0,
        "recent_accuracy": 0.0,
        "last_5_results": [False, False, False, False, False],
    },
    "sorting_algorithms": {
        "attempts": 9,
        "correct": 7,
        "recent_accuracy": 0.8,
        "last_5_results": [True, True, True, False, True],
    },
}
